### ISSUE TITLE
@okxweb3/crypto-lib using vulnerable packages

### ISSUE THREAD

**Issue by jonatns** [okx/js-wallet-sdk#104]
Our recent security audit discovered that `@okxweb3/crypto-lib` which is used by `@okxweb3/coin-bitcoin` is using an outdated `crypto-js` version that has a critical vulnerability. Also, `jsrsasign` has a high severity vulnerability.

<img width="1101" alt="Screenshot 2024-04-25 at 2 18 29 PM" src="https://github.com/okx/js-wallet-sdk/assets/5847682/3558c270-026b-4050-9906-d836e72a49db">

**Comment by leverwwz** [comment]
> Our recent security audit discovered that `@okxweb3/crypto-lib` which is used by `@okxweb3/coin-bitcoin` is using an outdated `crypto-js` version that has a critical vulnerability. Also, `jsrsasign` has a high severity vulnerability.
> 
> <img alt="Screenshot 2024-04-25 at 2 18 29 PM" width="1101" src="https://private-user-images.githubusercontent.com/5847682/325726256-3558c270-026b-4050-9906-d836e72a49db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NTA2OTQsIm5iZiI6MTcxNDY1MDM5NCwicGF0aCI6Ii81ODQ3NjgyLzMyNTcyNjI1Ni0zNTU4YzI3MC0wMjZiLTQwNTAtOTkwNi1kODM2ZTcyYTQ5ZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDJUMTE0NjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDk3NmQ1NzZjMGE0YzZiZjgzNzZjNjVhZDQ4NDdkNTkwNTRiNWFkMDQ1ZThkODIwNDJlNTdlMzMyNWMzZTY1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G-iPPEeYlM4rRaWqv3fJOpnGsEJEEydqadcDNiEPEMo">

@jonatns thanks for your issue, and we have analyse this, and the  vulnerability of jsrsasign is about RSA, reference is https://github.com/advisories/GHSA-rh63-9qcf-83gf.

later we will update jsrsasign lib as soon as possible.
