### ISSUE TITLE
The accuracy of floating-point operations in 'TypeScript'

### ISSUE THREAD

**Issue by Gu-code99** [okx/js-wallet-sdk#116]
module: coin-bitcoin
example:
txBuild.calculateTxSize() ->return {
        inputAmount,
        outputAmount,
        virtualSize,
        txHex
    };
    
virtualSize type is 'Number'(In TypeScript)
The type of feePerB is also 'Number'
estimateBtcFee = virtualSize  * feePerB，When fee is a decimal, there may be precision errors in floating-point operations
If virtualSize =350,feePerB=2.2,
The actual result should be 770, but the result in ts is 770.00000000001

**Comment by luyishisi** [comment]
Thank you for your feedback, we will arrange for optimization
