### ISSUE TITLE
[求助]发送交易例子

### ISSUE THREAD

**Issue by 3lang3** [okx/js-wallet-sdk#128]
先感谢okx团队提供了如此便捷的sdk工具处理钱包相关的逻辑

有个疑问🤔
如何使用okx生成的tx发送交易? 需要自己去实现各个钱包/链的请求吗？
如果这样，如何解析标准返回呢？

**Comment by 3lang3** [comment]
我尝试发送sui和aptos交易都失败了，生成的tx也无法使用sui/aptos官方sdk发送

**Comment by luyishisi** [comment]
SDK is the module responsible for generating transactions before broadcasting, so for security reasons, we will not directly integrate the broadcast function into the code.
If you need to broadcast transactions, there are different solutions for different chains. For example, BTC can be done directly on the web page:
https://mempool.space/zh/tx/push

ETH can be integrated into the code through the RPC method
