### ISSUE TITLE
[ton]bip39助记词sdk和okx浏览器存在差异

### ISSUE THREAD

**Issue by 3lang3** [okx/js-wallet-sdk#129]
助记词：`confirm viable multiply today canoe strike refuse job tomorrow orange opinion lunar`
sdk生成结果:
addr: UQA9qC8nQwLWddF19n3L9lWt38_bJoYz-88ylcw7qctDjwaT
pk: e9a7d059b100fe5153a27ab6eaf44d057ae2e0ce6ad02da79898305b56deee67

okx钱包:
addr: UQCer0BojkAKWNBTWzD0jn7Ss1uH5TADgQEwxS7c-RiS9VjX

**Comment by 3lang3** [comment]
找到问题了，bip39实际用的是`m/44'/607'/0'`, readme上的例子不准确

**Comment by debuggor** [comment]
thanks, updated
