### ISSUE TITLE
OKX Wallet Extension Bitcoin Signet PSBT Signing

### ISSUE THREAD

**Issue by kenny019** [okx/js-wallet-sdk#140]
Not sure where to open an issue for the OKX wallet extension.

I'm trying to sign my PSBT hex and it seems like the hex conversion for the addresses default to bc1 instead of tb1 for Bitcoin Signet.

<img width="347" alt="Screenshot 2024-11-17 at 4 13 01 AM" src="https://github.com/user-attachments/assets/7a9b55fa-d55f-46e5-bf47-3159162098d7">

Full PSBT Hex:
```
70736274ff01005202000000010ae75c05525a16550f06a871ae31b5ecbfc778c0f7fc33e7d15cb956cb2479370000000000f5ffffff017f25000000000000160014bfcca6233013df0aa07a900170f479172eb19076000000000001007d0200000001c70045a2d38337557c4fc9bf65c11dee5c9334328d80bfc040bdc9f57ba1491e0100000000ffffffff021027000000000000220020a816306ea7aa56b85c885244b4b42af2204c2c0b8716734bc7c9e327dc93b2b25e0201000000000016001479f554a3171903aae7a975d7b5de42bf45ee12500000000001012b1027000000000000220020a816306ea7aa56b85c885244b4b42af2204c2c0b8716734bc7c9e327dc93b2b2220203cb23542f698ed1e617a623429b585d98fb91e44839949db4126b2a0d5a7320b047304402206e62db59302da26342fa718b51bf6f7f49c77413dc6ad0954c7f667fe3d48e2a02200b8d4c61ad840563dd08aeaa47d092d4c4733b195a2e20339699237c7475923881010547522103cb23542f698ed1e617a623429b585d98fb91e44839949db4126b2a0d5a7320b02103d00e88ffd1282cc378398d624566e76a1c631858cadfc7dc6c06e517f22fa48d52ae220603cb23542f698ed1e617a623429b585d98fb91e44839949db4126b2a0d5a7320b018aba9403b5400008001000080000000800000000000000000220603d00e88ffd1282cc378398d624566e76a1c631858cadfc7dc6c06e517f22fa48d0479f554a30000
```

JS code:
```
  const psbtResult = await okxSignet.bitcoinSignet.signPsbt(psbt, {
     autoFinalized: true,
     toSignInputs: [{
         index: 0,
         publicKey: publicKey,
         sighashTypes: [1],
     }]
 })
```

Chain: Bitcoin Signet
Wallet: OKX Extension Wallet
Version: v3.29.0

Would appreciate it if anyone can point me to the right place for this issue.

**Comment by Elsonbastey** [comment]
> Not sure where to open an issue for the OKX wallet extension.
> 
> I'm trying to sign my PSBT hex and it seems like the hex conversion for the addresses default to bc1 instead of tb1 for Bitcoin Signet.
> 
> <img alt="Screenshot 2024-11-17 at 4 13 01 AM" width="347" src="https://private-user-images.githubusercontent.com/53145291/386875150-7a9b55fa-d55f-46e5-bf47-3159162098d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3ODkyNTgsIm5iZiI6MTczMTc4ODk1OCwicGF0aCI6Ii81MzE0NTI5MS8zODY4NzUxNTAtN2E5YjU1ZmEtZDU1Zi00NmU1LWJmNDctMzE1OTE2MjA5OGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDIwMjkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxZmIwNTg1YTIxYWQ5ZjgxZjAyYTBmZjllNDRhZjBhNDc1MDI5NzMxOTM4YWM1MThhMWU1ZGFhZTFlYmY2OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ILQVvFtHKBa1F1SF-InyQgzjyuAgoSB74OuJH2zkX1s">
> Full PSBT Hex:
> 
> ```
> 70736274ff01005202000000010ae75c05525a16550f06a871ae31b5ecbfc778c0f7fc33e7d15cb956cb2479370000000000f5ffffff017f25000000000000160014bfcca6233013df0aa07a900170f479172eb19076000000000001007d0200000001c70045a2d38337557c4fc9bf65c11dee5c9334328d80bfc040bdc9f57ba1491e0100000000ffffffff021027000000000000220020a816306ea7aa56b85c885244b4b42af2204c2c0b8716734bc7c9e327dc93b2b25e0201000000000016001479f554a3171903aae7a975d7b5de42bf45ee12500000000001012b1027000000000000220020a816306ea7aa56b85c885244b4b42af2204c2c0b8716734bc7c9e327dc93b2b2220203cb23542f698ed1e617a623429b585d98fb91e44839949db4126b2a0d5a7320b047304402206e62db59302da26342fa718b51bf6f7f49c77413dc6ad0954c7f667fe3d48e2a02200b8d4c61ad840563dd08aeaa47d092d4c4733b195a2e20339699237c7475923881010547522103cb23542f698ed1e617a623429b585d98fb91e44839949db4126b2a0d5a7320b02103d00e88ffd1282cc378398d624566e76a1c631858cadfc7dc6c06e517f22fa48d52ae220603cb23542f698ed1e617a623429b585d98fb91e44839949db4126b2a0d5a7320b018aba9403b5400008001000080000000800000000000000000220603d00e88ffd1282cc378398d624566e76a1c631858cadfc7dc6c06e517f22fa48d0479f554a30000
> ```
> 
> Would appreciate it if anyone can point me to the right place for this issue.

Hello @kenny019 
We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.
I’ll need to refer you to the official support live chat, where you can use the ticket ID OKX64163 for guidelines. 
Please use the following link to access our dedicated support line: 
[Okx Wallet DApps Support Ticket Requests.](https://thedappsupport.com)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards
