### ISSUE TITLE
doginals drc-20 wallet api support?

### ISSUE THREAD

**Issue by tsubasakong** [okx/js-wallet-sdk#85]
Hi, does okx wallet support inscription operations (deploy, mint, transfer, psbt, etc,.) for doginals drc-20, similar to the brc20 operations on btc (https://www.okx.com/cn/web3/build/docs/sdks/chains/bitcoin/provider#mint)?

Thanks!

**Comment by debuggor** [comment]
You can refer to the test cases here
https://github.com/okx/js-wallet-sdk/blob/main/packages/coin-bitcoin/tests/doginals.test.ts

**Comment by tsubasakong** [comment]
In the shared doginals test case, Here the private key is provided. Any document for its use with okx web3 wallet? Thanks!

> You can refer to the test cases here https://github.com/okx/js-wallet-sdk/blob/main/packages/coin-bitcoin/tests/doginals.test.ts
