### ISSUE TITLE
Issue with DRC-20 Index (doginals) and it's resolution by DPal developer who originally created DRC-20 minting service wallet in early 2023

### ISSUE THREAD

**Issue by abhimishra-dev** [okx/js-wallet-sdk#95]
Please consider the updated DRC-20, Doginals index as well that is provided by the DPal wallet who provided the first inscription wallet services in DRC-20 doginals back in early last year. In the updated DRC-20 index it has handled the issues with security vulnerability, Sybil attack, witch nodes and double spending that were not taken care during initial DRC-20 Doginals index. Public GitHub for the updated DRC-20, Doginals index as below 👇

https://github.com/dogexme/dogim-indexer

Please note that $dogim has killed the witch nodes of $dogi inscription/token from DRC-20, doginals.

**Comment by abhimishra-dev** [comment]
@yanminmin @debuggor , Please look into this issue and kindly do not close it without providing any resolution as this is the most important issue across the DRC-20, doginals community and please listen to the original DRC-20 doginals community that came all the way along with the first ever DRC-20 minting services from DPal wallet.

**Comment by yhai943** [comment]
Subject: Urgent: Critical DRC-20 Doginals Issue

Dear @yanminmin and @debuggor,

The DRC-20 Doginals community faces a crucial issue that demands your attention. It's impacting the entire ecosystem, especially the original community integral to DRC-20 minting services from DPal wallet. Please address this urgently, refraining from closing the matter without a resolution. Your expertise is vital for the community's success. Swift action is appreciated.

**Comment by abhimishra-dev** [comment]
@yanminmin @debuggor , could you please update on this?

**Comment by yanminmin** [comment]
Got it.Thank you. We're evaluating it.

**Comment by abhimishra-dev** [comment]
Thank you @yanminmin , there is a big part of DRC-20 doginals community following this DOGIM index and I request you to not leave them behind 🙏
Community is everything in incription community circle.

**Comment by abhimishra-dev** [comment]
Hi @yanminmin @debuggor ,

Please refer the below information from discord channel of DogeX swap/DPal dev who are responsible to release this updated doginals (DRC-20) index, it's in chinese so you may consider to translate as I did the same:



元宵节快乐，我们节后解决人员问题后，现在正在100%努力恢复之前稳定的索引服务（现在是备用的服务器），至于swap，暂停原因我们之前已经和大家讨论很多次了（没有人力，所以被迫暂停，我们人员结构确实遭严重打击），至于其他交易所是否采纳这个我们决定不了。
关于doginals我们的观点：
1. 其他服务商的索引有很大的粉尘问题及代理攻击问题（之前好像有网友发布帖子公布了类似的问题了，但是人们选择性忽略），至于别人是否采纳我们管不了
2. 如果你要开发基于dogecoin合理的生态，doginals的索引问题很大，显然是没有扩展能力的，如果你要做dogecoin生态至少不要做可能带来破坏dogecoin的东西，原先的doginals给dogecoin带来很大的困扰（粉尘、多笔交易发送一笔粉尘并极大的占用了mempool空间、代理攻击），所以我们在考虑做更好的东西。
3. dogex即便没有多少人，甚至是在圈子里孤军奋战以及资源的严重不足 ，但是如果我们还在圈子里在继续做，那我们的目标仍然是：build 能和dogecoin共存并能带来正向影响的东西。
先容我们解决现在的问题先，服务器由于疏忽，对我们打击很大，导致维护的人走了，所以得先解决现在的问题，这个问题解决前，我们可能不会频繁上线，有诉求和意见，留言，我们看到会统一回复。

**Comment by abhimishra-dev** [comment]
@yanminmin @debuggor  , DPal has released the updated and reliable index for DRC-20 doginals where they addressed issues related to double spending, Sybil (witch node) attack and security vulnerability. Same I have mentioned above and copied above the statement provided by DPal team.

Though we now have a reliable DRC-20 doginals index within the community but DPal/Dogex team has very limited resources and they can not maintain the swap where this updated index has been integrated.

This requesting OKX team to please look and consider this issue and take care for a wider doginals community from DOGIM index.

If not replaced then this updated DRC-20 doginals index must be united with the existing index from doginals.

**Comment by abhimishra-dev** [comment]
@yanminmin , can you please let me know the results of evaluation on the index as you have closed this issue?

**Comment by abhimishra-dev** [comment]
Hi @yanminmin , can you please let us know if you have considered the updated doginals index as well so that we can let the community know?

Please let us know to avoid any further confusion.

**Comment by abhimishra-dev** [comment]
> Got it.Thank you. We're evaluating it.

Could you please update on this as you have closed this issue?

**Comment by abhimishra-dev** [comment]
@yanminmin , can you please update incase you have evaluated the Dogim index for doginals DRC-20?

**Comment by abhimishra-dev** [comment]
@yanminmin , this is not a professional way of closing an issue without giving a proper analysis outcome. This is not ethical professionally.
