### ISSUE TITLE
Q: stacks-coin Account listing available?

### ISSUE THREAD

**Issue by dantrevino** [okx/js-wallet-sdk#98]
Stacks has the concept of an Account array in their wallet.  I see that I can generate new addresses with coin-stacks, but is there a way to see a list of accounts/addresses that have already been created for a specific seed? 

For reference: https://github.com/hirosystems/stacks.js/tree/main/packages/wallet-sdk#generate-a-wallet
```
interface Wallet {
  /** Used when generating app private keys, which encrypt app-specific data */
  salt: string;
  /** The private key associated with the root of a BIP39 keychain */
  rootKey: string;
  /** A private key used to encrypt configuration data */
  configPrivateKey: string;
  /** The encrypted secret key */
  encryptedSecretKey: string;
  /** A list of accounts generated by this wallet */
  accounts: Account[];
}
```
How can I find this `Account[]` with coin-stacks?

**Comment by yanminmin** [comment]
Look for stacks' rpc api, the sdk only provides offline signing.
